name: build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
      ALLREP_TOKEN: "${{secrets.ALLREP_TOKEN}}"
    steps:

      #### prepare #####################################################################################################
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get generic info"
        uses: ModelingValueGroup/generic-info@master

      #### build ######################################################################################################
      - name: "prepare ant"
        run:  |
          cat <<EOF >build.properties
          jdk.home.11=$JAVA_HOME
          path.variable.maven_repository=$HOME/.m2/repository
          EOF
          sed -i 's/filesetmanifest="mergewithoutmain"/filesetmanifest="merge"/' build.xml

      - name: "ant build"
        run: |
          rm -rf out
          ant
          cp out/artifacts/buildtools.jar ~

      - name: "generate/adjust some files if needed"
        run: |
          . <(java -jar ~/buildtools.jar)
          generateAll
          correctEols
          correctHeaders header

      - name: "push changes back to github"
        run:  |
          . <(java -jar ~/buildtools.jar)
          pushBackToGithub

      - name: "ant build again (in case something was adjusted in previous step)"
        run: |
          rm -rf out
          ant

      #### publish ####################################################################################################
      - name: "publish action-artifact buildtools.jar"
        uses: actions/upload-artifact@v1
        with:
          name: buildtools.jar
          path: out/artifacts/buildtools.jar

      #### test #######################################################################################################
      - name: "test"
        run: shellTools/tst/test.sh

      #### only master things from here on ############################################################################
      - name: "if master: fail if there is already a tag for this version"
        if: github.ref == 'refs/heads/master'
        run: |
          . <(java -jar ~/buildtools.jar)
          errorIfVersionTagExists

      - name: "if master: tag with version"
        if: github.ref == 'refs/heads/master'
        run:  |
          . <(java -jar ~/buildtools.jar)
          setVersionTag
          . <(catProjectSh '')
          echo "RELEASE_NAME=v$version" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" >> $GITHUB_ENV

      - name: "if master: create a release"
        uses: actions/create-release@v1
        if: github.ref == 'refs/heads/master'
        id: create_release
        with:
          tag_name: "${{env.RELEASE_NAME}}"
          release_name: "${{env.RELEASE_NAME}}"
          body: "release ${{env.RELEASE_NAME}}"
          draft: false
          prerelease: false

      - name: "if master: upload as release"
        uses: actions/upload-release-asset@v1
        if: github.ref == 'refs/heads/master'
        with:
          upload_url: "${{steps.create_release.outputs.upload_url}}"
          asset_path: out/artifacts/buildtools.jar
          asset_name: buildtools.jar
          asset_content_type: application/java-archive

      - name: "if master: upload as package"
        uses: ModelingValueGroup/upload-maven-package-action@master
        if: github.ref == 'refs/heads/master'
        with:
          file: "out/artifacts/buildtools.jar"
