name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "install packages"
        run: apt-get install xmlstarlet jq maven

      - name: "build"
        run: |
          ## concat all script to for one:
          for f in src/*.sh; do
            echo "#!/usr/bin/env bash"
            echo "### $f"
            cat $f
            echo
          done > buildTools.sh

      - name: "test"
        run: tst/test.sh
        env:
          INPUT_TOKEN:  "${{ secrets.GITHUB_TOKEN }}"

      - name: upload as package"
        uses: ModelingValueGroup/upload-maven-package-action@master
        with:
          file: "buildTools.sh"
          token: "${{ secrets.GITHUB_TOKEN }}"
