name: build
on:
  push:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "build"
        run: |
          ant

      - name: "test"
        run: |
          sudo apt-get install xmlstarlet jq maven
          shellTools/tst/test.sh
        env:
          INPUT_TOKEN:  "${{ secrets.GITHUB_TOKEN }}"

#      - name: "upload as package"
#        uses: ModelingValueGroup/upload-maven-package-action@master
#        if: github.ref == 'refs/heads/master'
#        with:
#          file: "buildTools.sh"
#          token: "${{ secrets.GITHUB_TOKEN }}"
